import javax.swing.*;

/**
 * This class is used to show the achievements of the player.
 * @author paulrecker
 */
public class Achievements extends javax.swing.JFrame {

    /**
     * Creates new form GameGuide
     */
    private String userName;
    public Achievements(String user ) {
        userName = user;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Achievements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Achievements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Achievements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Achievements.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        setAchievements();
        this.setVisible(true);
    }


    /**
     * This method is used to set the achievements of the player.
     * The data is fetched from a database.
     */
    public void setAchievements() {
        boolean[] achieved = DBConnect.getAchievements(userName);

        if (achieved[0]) {
            a0.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a0b.png")));
        }
        if (achieved[1]){
            a1.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a1b.png")));
        }
         if (achieved[2]){
            a2.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a2b.png")));
        }
         if (achieved[3]){
            a3.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a3b.png")));
        }
         if (achieved[4]){
            a4.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a4b.png")));
        }
         if (achieved[5]){
            a5.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a5b.png")));
        }

    }






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    /**
     * This method initialized the form.
     */
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        a0 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(159, 155, 167));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville", 1, 36)); // NOI18N
        jLabel1.setText("Achievements");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, 10));

        a0.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a0w.png"))); // NOI18N
        jPanel1.add(a0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 110));

        jLabel2.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel2.setText("Card Shark");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel10.setText("Beginner");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel11.setText("Low Roller");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel12.setText("Solid Player");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel13.setText("Advantage Player");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel14.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        jLabel14.setText("High Roller");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        a1.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a1w.png"))); // NOI18N
        jPanel1.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        a2.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a2w.png"))); // NOI18N
        jPanel1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        a3.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a3w.png"))); // NOI18N
        jPanel1.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        a4.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a4w.png"))); // NOI18N
        jPanel1.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        a5.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("a5w.png"))); // NOI18N
        jPanel1.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 430));

        pack();
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JLabel a0;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration
}
