/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 * This is the class that is used to Login to ones BlackJack account.
 * @author paulrecker
 */
public class BlackJackLogIn extends javax.swing.JFrame {

    /**
     * Creates new form BlackJackLogIn
     */
    public BlackJackLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logInPanel = new javax.swing.JPanel();
        loginChanger = new javax.swing.JLabel();
        loginUsernameLabel = new javax.swing.JLabel();
        loginUsernameTF = new javax.swing.JTextField();
        loginUsernameSeperator = new javax.swing.JSeparator();
        loginPasswordLabel = new javax.swing.JLabel();
        loginPasswordPF = new javax.swing.JPasswordField();
        loginPasswordSeperator = new javax.swing.JSeparator();
        loginButton = new javax.swing.JLabel();
        loginBG = new javax.swing.JLabel();
        signupPanel = new javax.swing.JPanel();
        signupChanger = new javax.swing.JLabel();
        signupUsernameLabel = new javax.swing.JLabel();
        signupUsernameTF = new javax.swing.JTextField();
        signupUsernameSeperator = new javax.swing.JSeparator();
        signupEmailLabel = new javax.swing.JLabel();
        signupEmailTF = new javax.swing.JTextField();
        signupEmailSeperator = new javax.swing.JSeparator();
        signupPasswordLabel = new javax.swing.JLabel();
        signupPasswordPF = new javax.swing.JPasswordField();
        signupPasswordSeperator = new javax.swing.JSeparator();
        signupButton = new javax.swing.JLabel();
        signupTCCheckBox = new javax.swing.JCheckBox();
        signupTCLabel = new javax.swing.JLabel();
        signupBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginChanger.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("LogInSignUpChange.png"))); // NOI18N
        loginChanger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginChangerMouseReleased(evt);
            }
        });
        logInPanel.add(loginChanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        loginUsernameLabel.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        loginUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginUsernameLabel.setText("Username");
        logInPanel.add(loginUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        loginUsernameTF.setBackground(new java.awt.Color(60, 60, 60));
        loginUsernameTF.setFont(new java.awt.Font("Baskerville", 2, 14)); // NOI18N
        loginUsernameTF.setForeground(new java.awt.Color(204, 204, 204));
        loginUsernameTF.setText("Enter Username");
        loginUsernameTF.setBorder(null);
        logInPanel.add(loginUsernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 320, 30));
        logInPanel.add(loginUsernameSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 320, -1));

        loginPasswordLabel.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        loginPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordLabel.setText("Password");
        logInPanel.add(loginPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        loginPasswordPF.setBackground(new java.awt.Color(60, 60, 60));
        loginPasswordPF.setFont(new java.awt.Font("Baskerville", 2, 14)); // NOI18N
        loginPasswordPF.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordPF.setText("ExamplePassword");
        loginPasswordPF.setBorder(null);
        logInPanel.add(loginPasswordPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 246, 320, 30));
        logInPanel.add(loginPasswordSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 320, -1));

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("LoginButton.png"))); // NOI18N
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginButtonMouseReleased(evt);
            }
        });
        logInPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        loginBG.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("BlackJackLogin.png"))); // NOI18N
        logInPanel.add(loginBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        getContentPane().add(logInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        signupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupChanger.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("SignUpLogInChange.png"))); // NOI18N
        signupChanger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signupChangerMouseReleased(evt);
            }
        });
        signupPanel.add(signupChanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        signupUsernameLabel.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        signupUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        signupUsernameLabel.setText("Username");
        signupPanel.add(signupUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        signupUsernameTF.setBackground(new java.awt.Color(60, 60, 60));
        signupUsernameTF.setFont(new java.awt.Font("Baskerville", 2, 14)); // NOI18N
        signupUsernameTF.setForeground(new java.awt.Color(204, 204, 204));
        signupUsernameTF.setText("Enter Username");
        signupUsernameTF.setBorder(null);
        signupPanel.add(signupUsernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 320, 30));
        signupPanel.add(signupUsernameSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 320, -1));

        signupEmailLabel.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        signupEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        signupEmailLabel.setText("Email");
        signupPanel.add(signupEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        signupEmailTF.setBackground(new java.awt.Color(60, 60, 60));
        signupEmailTF.setFont(new java.awt.Font("Baskerville", 2, 14)); // NOI18N
        signupEmailTF.setForeground(new java.awt.Color(204, 204, 204));
        signupEmailTF.setText("Enter Email");
        signupEmailTF.setBorder(null);
        signupEmailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupEmailTFActionPerformed(evt);
            }
        });
        signupPanel.add(signupEmailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 320, 30));
        signupPanel.add(signupEmailSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 320, -1));

        signupPasswordLabel.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        signupPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        signupPasswordLabel.setText("Password");
        signupPanel.add(signupPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 272, -1, -1));

        signupPasswordPF.setBackground(new java.awt.Color(60, 60, 60));
        signupPasswordPF.setFont(new java.awt.Font("Baskerville", 2, 14)); // NOI18N
        signupPasswordPF.setForeground(new java.awt.Color(255, 255, 255));
        signupPasswordPF.setText("ExamplePassword");
        signupPasswordPF.setBorder(null);
        signupPanel.add(signupPasswordPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 320, 30));
        signupPanel.add(signupPasswordSeperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 320, -1));

        signupButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("SignupButton.png"))); // NOI18N
        signupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signupButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signupButtonMouseReleased(evt);
            }
        });
        signupPanel.add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        signupTCCheckBox.setFont(new java.awt.Font("Baskerville", 0, 13)); // NOI18N
        signupTCCheckBox.setText("Agree to");
        signupTCCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupTCCheckBoxActionPerformed(evt);
            }
        });
        signupPanel.add(signupTCCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        signupTCLabel.setFont(new java.awt.Font("Baskerville", 0, 13)); // NOI18N
        signupTCLabel.setForeground(new java.awt.Color(80, 80, 80));
        signupTCLabel.setText("<html> <body> <u>Terms and Conditions<u/> </body> </html>");
        signupTCLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signupTCLabelMouseReleased(evt);
            }
        });
        signupPanel.add(signupTCLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 379, -1, 20));

        signupBG.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("BlackJackLogin.png"))); // NOI18N
        signupPanel.add(signupBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        getContentPane().add(signupPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        // TODO add your handling code here:
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("LoginButtonPRESSED.png")));// NOI18N

        String username = loginUsernameTF.getText();
        String password = loginPasswordPF.getText();
        if (DBConnect.checkPassword(username, password) && !username.equals("Dealer")) {
            View view = new View(username);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect username or password");
        }
    }//GEN-LAST:event_loginButtonMousePressed

    private void loginButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseReleased
        // TODO add your handling code here:
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("LoginButton.png"))); // NOI18N
    }//GEN-LAST:event_loginButtonMouseReleased

    private void loginChangerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginChangerMouseReleased
        // TODO add your handling code here:
        logInPanel.setVisible(false);
        signupPanel.setVisible(true);
    }//GEN-LAST:event_loginChangerMouseReleased

    private void signupChangerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupChangerMouseReleased
        // TODO add your handling code here:
        logInPanel.setVisible(true);
        signupPanel.setVisible(false);
    }//GEN-LAST:event_signupChangerMouseReleased

    private void signupButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupButtonMousePressed
        // TODO add your handling code here:
        signupButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("SignupButtonPRESSED.png"))); // NOI18N
        String username = signupUsernameTF.getText();
        String password = signupPasswordPF.getText();
        String email = signupEmailTF.getText();
        boolean TC = signupTCCheckBox.isSelected();

        if(TC && !DBConnect.isEmailAlreadyUsed(email) && !DBConnect.isUsernameAlreadyUsed(username) && Tools.isValidEmailAddress(email)){
            DBConnect.createNewUser(username, password, email);
            JOptionPane.showMessageDialog(this, "Account created successfully. Please Login");
        } else if ((DBConnect.isEmailAlreadyUsed(email) || DBConnect.isUsernameAlreadyUsed(username) ) && TC){
            JOptionPane.showMessageDialog(this, "Email or Password already used");
        } else if (!TC){
            JOptionPane.showMessageDialog(this, "Please accept the Terms and Conditions");
        } else if (!Tools.isValidEmailAddress(email)){
            JOptionPane.showMessageDialog(this, "Please enter a valid email address");
        } else {
            JOptionPane.showMessageDialog(this, "Something went wrong");
        }
        signupButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("SignupButton.png")));
    }//GEN-LAST:event_signupButtonMousePressed

    private void signupButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupButtonMouseReleased
        // TODO add your handling code here:
        signupButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("SignupButton.png"))); // NOI18N
    }//GEN-LAST:event_signupButtonMouseReleased

    private void signupEmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupEmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupEmailTFActionPerformed

    private void signupTCCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupTCCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupTCCheckBoxActionPerformed

    private void signupTCLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupTCLabelMouseReleased
        // TODO add your handling code here:
        try {
         
        Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=a3Z7zEc7AXQ"));
         
    } catch (IOException | URISyntaxException e1) {
        e1.printStackTrace();
    }
    }//GEN-LAST:event_signupTCLabelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJackLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJackLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJackLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJackLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJackLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel logInPanel;
    private javax.swing.JLabel loginBG;
    private javax.swing.JLabel loginButton;
    private javax.swing.JLabel loginChanger;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JPasswordField loginPasswordPF;
    private javax.swing.JSeparator loginPasswordSeperator;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JSeparator loginUsernameSeperator;
    private javax.swing.JTextField loginUsernameTF;
    private javax.swing.JLabel signupBG;
    private javax.swing.JLabel signupButton;
    private javax.swing.JLabel signupChanger;
    private javax.swing.JLabel signupEmailLabel;
    private javax.swing.JSeparator signupEmailSeperator;
    private javax.swing.JTextField signupEmailTF;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JLabel signupPasswordLabel;
    private javax.swing.JPasswordField signupPasswordPF;
    private javax.swing.JSeparator signupPasswordSeperator;
    private javax.swing.JCheckBox signupTCCheckBox;
    private javax.swing.JLabel signupTCLabel;
    private javax.swing.JLabel signupUsernameLabel;
    private javax.swing.JSeparator signupUsernameSeperator;
    private javax.swing.JTextField signupUsernameTF;
    // End of variables declaration//GEN-END:variables
}
