import javax.swing.*;


/**
 * This class creates a GUI Game Guide
 * @author paulrecker
 */
public class GameGuide extends javax.swing.JFrame {

    /**
     * Creates new form GameGuide
     */
    public GameGuide() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.setTitle("BlackJack - Game Guide");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(159, 155, 167));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville", 1, 36)); // NOI18N
        jLabel1.setText("Game Guide");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Baskerville", 0, 16)); // NOI18N
        jLabel2.setText("<html>\n<p>Der Croupier gibt den Spielern zwei Karten und sich selbst zwei Karten (1 Karte aufgedeckt, die andere verdeckt).</p>\n<p></p>\n<p>Blackjack Kartenwerte: Alle Karten zählen beim Blackjack ihren Nennwert: Bildkarten = 10, das Ass entweder als 1 oder 11. Die Farbe der Karten hat beim Blackjack keine Bedeutung. Die Summe einer Hand ist die Summe der Kartenwerte in der Hand.</p>\n<p></p>\n<p>Die Spieler müssen entscheiden, ob sie halten (stand), ziehen (hit), verdoppeln (double down) oder teilen (split) wollen. Teilen kann nur bei zwei Pärchen stattfinden.</p>\n <p></p>\n<p>Der Croupier handelt als letzter und muss bei 16 oder weniger ziehen (hit) und von 17 bis 21 halten (stand).\nSpieler gewinnen, wenn ihre Blackjack Hand höher als die des Croupiers ist, oder sie 21 oder weniger haben, oder wenn der Croupier überkauft (bust), d. H. wenn er die 21 übersteigt.</p>\n</html>");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 640, 300));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 10));

        jLabel3.setFont(new java.awt.Font("Baskerville", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Quelle: https://www.888slots.de/blog/blackjack-strategie-anleitung/blackjack-regeln");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
