import javax.swing.*;

/**
 * This class creates a gui where the player can change settings
 * @author paulrecker
 */
public class Settings extends javax.swing.JFrame {
    private String userName;
    public Settings(String username) {
        userName = username;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userPassTF = new javax.swing.JTextField();
        userUserTF = new javax.swing.JTextField();
        userSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        mailPassTF = new javax.swing.JTextField();
        mailMailTF = new javax.swing.JTextField();
        mailSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        passNewPassTF = new javax.swing.JTextField();
        passOldPassTF = new javax.swing.JTextField();
        passSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(139, 130, 155));
        setForeground(new java.awt.Color(139, 130, 155));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(159, 155, 167));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville", 1, 36)); // NOI18N
        jLabel1.setText("Settings");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 17, -1, -1));

        jLabel2.setFont(new java.awt.Font("Baskerville", 0, 16)); // NOI18N
        jLabel2.setText("Change Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 670, -1));

        userPassTF.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        userPassTF.setText("Password");
        userPassTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPassTFActionPerformed(evt);
            }
        });
        jPanel1.add(userPassTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 230, -1));

        userUserTF.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        userUserTF.setText("New Username");
        jPanel1.add(userUserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 230, -1));

        userSubmit.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        userSubmit.setText("Submit");
        userSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(userSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville", 0, 16)); // NOI18N
        jLabel3.setText("Change Mail");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 670, -1));

        mailPassTF.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        mailPassTF.setText("Password");
        jPanel1.add(mailPassTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 230, -1));

        mailMailTF.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        mailMailTF.setText("New Mail");
        jPanel1.add(mailMailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, -1));

        mailSubmit.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        mailSubmit.setText("Submit");
        mailSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(mailSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Baskerville", 0, 16)); // NOI18N
        jLabel4.setText("Change Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 670, -1));

        passNewPassTF.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        passNewPassTF.setText("New Passwort");
        jPanel1.add(passNewPassTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 230, -1));

        passOldPassTF.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        passOldPassTF.setText("Old Password");
        jPanel1.add(passOldPassTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 230, -1));

        passSubmit.setFont(new java.awt.Font("Baskerville", 0, 14)); // NOI18N
        passSubmit.setText("Submit");
        passSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(passSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Baskerville", 2, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Version 1.0.0 - Paul Recker");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userPassTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPassTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPassTFActionPerformed

    private void userSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSubmitActionPerformed
        // TODO add your handling code here:
        // declares variables and saves username and password
        String user = userUserTF.getText();
        String pass = userPassTF.getText();
        // checks in DBConnect if Password is valid
        if (DBConnect.checkPassword(userName, pass)) {
            // checks in DBConnect if Username is not already in use
            if (!DBConnect.isUsernameAlreadyUsed(user)) {
                // Changes the Username in the Database using DBConnect
                DBConnect.changeUsername(userName, user);
                JOptionPane.showMessageDialog(this, "Username changed. Game needs to restart to apply changes.");
                System.exit(0);
            } else {
                // shows error message if Username is already in use
                JOptionPane.showMessageDialog(this, "Username already in use");
            }
        } else {
            // shows error message if Password is not valid
            JOptionPane.showMessageDialog(this, "Password is not valid");
        }
    }//GEN-LAST:event_userSubmitActionPerformed

    private void mailSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailSubmitActionPerformed
        // TODO add your handling code here:
        // declares variables mail and password, then it checks the password and changes the mail if correct
        String mail = mailMailTF.getText();
        String pass = mailPassTF.getText();
        if (DBConnect.checkPassword(userName, pass)) {
            if (!DBConnect.isEmailAlreadyUsed(mail)) {
                DBConnect.changeMail(userName, mail);
                JOptionPane.showMessageDialog(this, "Mail changed. Game needs to restart to apply changes.");
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(this, "Email already in use");
        }
        } else {
            JOptionPane.showMessageDialog(this, "Password is not valid");
    }

    }//GEN-LAST:event_mailSubmitActionPerformed

    private void passSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passSubmitActionPerformed
        // TODO add your handling code here:
        // declares variables and saves old and new password then it uses DBConnect to check if the password is valid than it changes the password
        String oldPass = passOldPassTF.getText();
        String newPass = passNewPassTF.getText();
        if (DBConnect.checkPassword(userName, oldPass)) {
            DBConnect.changePassword(userName, newPass);
            // shows success message and closes the window
            JOptionPane.showMessageDialog(this, "Password changed. Game needs to restart to apply changes.");
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(this, "Password is not valid");
        }
    }


    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField mailMailTF;
    private javax.swing.JTextField mailPassTF;
    private javax.swing.JButton mailSubmit;
    private javax.swing.JTextField passNewPassTF;
    private javax.swing.JTextField passOldPassTF;
    private javax.swing.JButton passSubmit;
    private javax.swing.JTextField userPassTF;
    private javax.swing.JButton userSubmit;
    private javax.swing.JTextField userUserTF;
    // End of variables declaration//GEN-END:variables

}
