/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.util.HashMap;

/**
 * This class is the main GUI for the Game of Black Jack (ViewController)
 * @author paulrecker
 */
public class View extends javax.swing.JFrame {

    GameRunner gameRunner;
    private boolean betPlaced = false;
    private int xAxisPlayer, xAxisSplitPlayer;
    private int xAxisDealer;
    private String userName;
    /**
     * Creates new form BlackJack
     */
    public View(String pUsername) {
        userName = pUsername;
        xAxisPlayer = 197;
        xAxisSplitPlayer = 0;
        xAxisDealer = 0;
        initComponents();
        gameRunner = new GameRunner(this);
        this.setVisible(true);
        infoMap.setVisible(false);
        this.setResizable(false);
        updateBalance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoMap = new javax.swing.JPanel();
        infoMapUsernameLabel = new javax.swing.JLabel();
        infoMapHistoryButton = new javax.swing.JLabel();
        infoMapAchievementsButton = new javax.swing.JLabel();
        infoMapDailyBonusButton = new javax.swing.JLabel();
        infoMapGameGuideButton = new javax.swing.JLabel();
        infoMapSettingsButton = new javax.swing.JLabel();
        infoMapLogOutButton = new javax.swing.JLabel();
        infoMapBG = new javax.swing.JLabel();
        bG = new javax.swing.JPanel();
        playerCardJPanel = new javax.swing.JPanel();
        playerSplitCardJPanel = new javax.swing.JPanel();
        dealerCardJPanel = new javax.swing.JPanel();
        menuNotifications = new javax.swing.JLabel();
        menuPlayerHandSum = new javax.swing.JLabel();
        menuDealerHandSum = new javax.swing.JLabel();
        menuDealerHandSumInt = new javax.swing.JLabel();
        menuPlayerHandSumInt = new javax.swing.JLabel();
        menuBalance = new javax.swing.JLabel();
        menuBetInputTF = new javax.swing.JTextField();
        menuBetInputLabel = new javax.swing.JLabel();
        menuPlaceBetButton = new javax.swing.JLabel();
        menuAccName = new javax.swing.JLabel();
        menuAccButton = new javax.swing.JLabel();
        hitButton = new javax.swing.JLabel();
        standButton = new javax.swing.JLabel();
        splitButton = new javax.swing.JLabel();
        doubleButton = new javax.swing.JLabel();
        pF = new javax.swing.JLabel();




        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(80, 80, 80));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoMap.setOpaque(false);
        infoMap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoMapUsernameLabel.setFont(new java.awt.Font("Baskerville", 1, 16)); // NOI18N
        infoMapUsernameLabel.setText(userName);
        infoMapUsernameLabel.setToolTipText("");
        infoMap.add(infoMapUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 13, 150, -1));

        infoMapHistoryButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapHistoryButton.png"))); // NOI18N
        infoMapHistoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoMapHistoryButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                infoMapHistoryButtonMouseReleased(evt);
            }
        });
        infoMap.add(infoMapHistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 46, -1, -1));

        infoMapAchievementsButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapAchievementsButton.png"))); // NOI18N
        infoMapAchievementsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoMapAchievementsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                infoMapAchievementsButtonMouseReleased(evt);
            }
        });
        infoMap.add(infoMapAchievementsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 86, -1, -1));

        infoMapDailyBonusButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapDailyBonusButton.png"))); // NOI18N
        infoMapDailyBonusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoMapDailyBonusButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                infoMapDailyBonusButtonMouseReleased(evt);
            }
        });
        infoMap.add(infoMapDailyBonusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 126, -1, -1));

        infoMapGameGuideButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapGameGuideButton.png"))); // NOI18N
        infoMapGameGuideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoMapGameGuideButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                infoMapGameGuideButtonMouseReleased(evt);
            }
        });
        infoMap.add(infoMapGameGuideButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 166, -1, -1));

        infoMapSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapSettingsButton.png"))); // NOI18N
        infoMapSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoMapSettingsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                infoMapSettingsButtonMouseReleased(evt);
            }
        });
        infoMap.add(infoMapSettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 206, -1, -1));

        infoMapLogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("LogOutButton.png"))); // NOI18N
        infoMapLogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoMapLogOutButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                infoMapLogOutButtonMouseReleased(evt);
            }
        });
        infoMap.add(infoMapLogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 270, -1, -1));

        infoMapBG.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMap.png"))); // NOI18N
        infoMap.add(infoMapBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(infoMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(999, 72, -1, 330));


        bG.setBackground(new java.awt.Color(30, 30, 30));
        bG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        playerCardJPanel.setOpaque(false);
        playerSplitCardJPanel.setOpaque(false);
        dealerCardJPanel.setOpaque(false);
        bG.add(playerCardJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 305, 170));
        bG.add(playerSplitCardJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 450, 200, 170));
        bG.add(dealerCardJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 74, 300, 170));
        playerCardJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        playerSplitCardJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        dealerCardJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        menuNotifications.setFont(new java.awt.Font("Baskerville", 0, 18)); // NOI18N
        bG.add(menuNotifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 19, 390, 30));

        menuPlayerHandSum.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        menuPlayerHandSum.setText("Player :");
        bG.add(menuPlayerHandSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        menuDealerHandSum.setFont(new java.awt.Font("Baskerville", 1, 18)); // NOI18N
        menuDealerHandSum.setText("Dealer :");
        bG.add(menuDealerHandSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        menuDealerHandSumInt.setFont(new java.awt.Font("Baskerville", 1, 14)); // NOI18N
        menuDealerHandSumInt.setText("0");
        bG.add(menuDealerHandSumInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 44, -1, -1));

        menuPlayerHandSumInt.setFont(new java.awt.Font("Baskerville", 1, 14)); // NOI18N
        menuPlayerHandSumInt.setText("0");
        bG.add(menuPlayerHandSumInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 13, -1, -1));

        menuBalance.setFont(new java.awt.Font("Baskerville", 1, 24)); // NOI18N
        menuBalance.setText("$0.00");
        bG.add(menuBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        menuBetInputTF.setBackground(new java.awt.Color(115, 107, 128));
        menuBetInputTF.setFont(new java.awt.Font("Baskerville", 1, 24)); // NOI18N
        menuBetInputTF.setText("0.00");
        menuBetInputTF.setBorder(null);
        menuBetInputTF.setOpaque(true);
        bG.add(menuBetInputTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 90, 30));

        menuBetInputLabel.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("BetInput.png"))); // NOI18N
        bG.add(menuBetInputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 130, 50));

        menuPlaceBetButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("PlaceBet.png"))); // NOI18N
        menuPlaceBetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuPlaceBetButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuPlaceBetButtonMouseReleased(evt);
            }
        });
        bG.add(menuPlaceBetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        menuAccName.setFont(new java.awt.Font("Baskerville", 1, 13)); // NOI18N
        menuAccName.setText(userName);
        bG.add(menuAccName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 27, -1, -1));

        menuAccButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("AccountButton.png"))); // NOI18N
        menuAccButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuAccButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuAccButtonMouseReleased(evt);
            }
        });
        bG.add(menuAccButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        hitButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("HitButton.png"))); // NOI18N
        hitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hitButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hitButtonMouseReleased(evt);
            }
        });
        bG.add(hitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        standButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("StandButton.png"))); // NOI18N
        standButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                standButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                standButtonMouseReleased(evt);
            }
        });
        bG.add(standButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 600, -1, -1));

        splitButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("SplitButton.png"))); // NOI18N
        splitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                splitButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                splitButtonMouseReleased(evt);
            }
        });
        bG.add(splitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 670, -1, -1));

        doubleButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("DoubleButton.png"))); // NOI18N
        doubleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                doubleButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                doubleButtonMouseReleased(evt);
            }
        });
        bG.add(doubleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, -1, -1));

        pF.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("PF.jpg"))); // NOI18N
        bG.add(pF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(bG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPlaceBetButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPlaceBetButtonMousePressed
        if (menuPlaceBetButton.isEnabled()) {
            menuPlaceBetButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("PlaceBetPRESSED.png"))); // NOI18N
            double bet = Double.parseDouble(menuBetInputTF.getText());
            if (bet <= Double.parseDouble(gameRunner.getPlayerData("balance")) && bet >= 1) {
                WavPlayer.startEffect("src/main/resources/chipsSettle.wav");
                menuPlaceBetButton.setEnabled(false);
                gameRunner.firstBet(bet);
                betPlaced = true;
                updateBalance();
            } else {
                menuPlaceBetButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("PlaceBet.png"))); // NOI18N
                JOptionPane.showMessageDialog(this, "Balance is too low or you bet below the minimum", "BlackJack", JOptionPane.PLAIN_MESSAGE);
            }

        }
    }//GEN-LAST:event_menuPlaceBetButtonMousePressed

    private void menuPlaceBetButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPlaceBetButtonMouseReleased
         menuPlaceBetButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("PlaceBet.png"))); // NOI18N
    }//GEN-LAST:event_menuPlaceBetButtonMouseReleased

    private void menuAccButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAccButtonMousePressed
        menuAccButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("AccountButtonPRESSED.png"))); // NOI18N
        
        if(!infoMap.isVisible()){
            infoMap.setVisible(true);
        } else if (infoMap.isVisible()){
            infoMap.setVisible(false);
        }
    }//GEN-LAST:event_menuAccButtonMousePressed

    private void menuAccButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAccButtonMouseReleased
        menuAccButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("AccountButton.png"))); // NOI18N
    }//GEN-LAST:event_menuAccButtonMouseReleased

    private void hitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitButtonMousePressed
        hitButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("HitButtonPRESSED.png"))); // NOI18N
        if(hitButton.isEnabled() && betPlaced){
            WavPlayer.startEffect("src/main/resources/hitSound.wav");
            try {
                Thread.sleep(1500);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            WavPlayer.startEffect("src/main/resources/cardDraw.wav");
            gameRunner.hitAction();

        }
    }//GEN-LAST:event_hitButtonMousePressed

    private void hitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitButtonMouseReleased
        hitButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("HitButton.png"))); // NOI18N
    }//GEN-LAST:event_hitButtonMouseReleased

    private void standButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_standButtonMousePressed
        standButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("StandButtonPRESSED.png"))); // NOI18N
        if (standButton.isEnabled() && betPlaced) {
            WavPlayer.startEffect("src/main/resources/standSound.wav");
            gameRunner.standAction();
        }
    }//GEN-LAST:event_standButtonMousePressed

    private void standButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_standButtonMouseReleased
        standButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("StandButton.png"))); // NOI18N
    }//GEN-LAST:event_standButtonMouseReleased

    private void splitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_splitButtonMousePressed
        splitButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("SplitButtonPRESSED.png"))); // NOI18N
        if (splitButton.isEnabled() && betPlaced) {
            WavPlayer.startEffect("src/main/resources/chipsSettle.wav");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            gameRunner.splitAction();
        }
    }//GEN-LAST:event_splitButtonMousePressed

    private void splitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_splitButtonMouseReleased
        splitButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("SplitButton.png"))); // NOI18N
    }//GEN-LAST:event_splitButtonMouseReleased

    private void doubleButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doubleButtonMousePressed
        doubleButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("DoubleButtonPRESSED.png"))); // NOI18N
        if (doubleButton.isEnabled() && betPlaced) {
            WavPlayer.startEffect("src/main/resources/hitSound.wav");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            WavPlayer.startEffect("src/main/resources/chipsSettle.wav");
            try {
                Thread.sleep(1500);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            WavPlayer.startEffect("src/main/resources/cardDraw.wav");
            gameRunner.doubleAction();
        }
    }//GEN-LAST:event_doubleButtonMousePressed

    private void doubleButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doubleButtonMouseReleased
        doubleButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("DoubleButton.png"))); // NOI18N
    }//GEN-LAST:event_doubleButtonMouseReleased

    private void infoMapLogOutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapLogOutButtonMousePressed
        infoMapLogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("LogOutButtonPRESSED.png"))); // NOI18N
        BlackJackLogIn.main(null);
        this.dispose();
    }//GEN-LAST:event_infoMapLogOutButtonMousePressed

    private void infoMapLogOutButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapLogOutButtonMouseReleased
        infoMapLogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("LogOutButton.png"))); // NOI18N
    }//GEN-LAST:event_infoMapLogOutButtonMouseReleased

    private void infoMapHistoryButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapHistoryButtonMousePressed
        infoMapHistoryButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapHistoryButtonPRESSED.png"))); // NOI18N
    }//GEN-LAST:event_infoMapHistoryButtonMousePressed

    private void infoMapHistoryButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapHistoryButtonMouseReleased
        infoMapHistoryButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapHistoryButton.png"))); // NOI18N
        new History(gameRunner.getGameHistory(), userName);
    }//GEN-LAST:event_infoMapHistoryButtonMouseReleased

    private void infoMapAchievementsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapAchievementsButtonMousePressed
        infoMapAchievementsButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapAchievementsButtonPRESSED.png"))); // NOI18N
    }//GEN-LAST:event_infoMapAchievementsButtonMousePressed

    private void infoMapAchievementsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapAchievementsButtonMouseReleased
        infoMapAchievementsButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapAchievementsButton.png"))); // NOI18N
        new Achievements(userName);
    }//GEN-LAST:event_infoMapAchievementsButtonMouseReleased

    private void infoMapDailyBonusButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapDailyBonusButtonMousePressed
        infoMapDailyBonusButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapDailyBonusButtonPRESSED.png"))); // NOI18N

    }//GEN-LAST:event_infoMapDailyBonusButtonMousePressed

    private void infoMapDailyBonusButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapDailyBonusButtonMouseReleased
        infoMapDailyBonusButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapDailyBonusButton.png"))); // NOI18N
        gameRunner.dailyBonus();
    }//GEN-LAST:event_infoMapDailyBonusButtonMouseReleased

    private void infoMapGameGuideButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapGameGuideButtonMousePressed
        infoMapGameGuideButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapGameGuideButtonPRESSED.png"))); // NOI18N
    }//GEN-LAST:event_infoMapGameGuideButtonMousePressed

    private void infoMapGameGuideButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapGameGuideButtonMouseReleased
        infoMapGameGuideButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapGameGuideButton.png"))); // NOI18N
        new GameGuide();
    }//GEN-LAST:event_infoMapGameGuideButtonMouseReleased

    private void infoMapSettingsButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapSettingsButtonMousePressed
        infoMapSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapSettingsButtonPRESSED.png"))); // NOI18N
    }//GEN-LAST:event_infoMapSettingsButtonMousePressed

    private void infoMapSettingsButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMapSettingsButtonMouseReleased
        infoMapSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("InfoMapSettingsButton.png"))); // NOI18N
        new Settings(userName);
    }//GEN-LAST:event_infoMapSettingsButtonMouseReleased


    /**
     * This sets messages in the notification bar
     * @param pMessage
     */
    public void setNotiMessage(String pMessage){
        menuNotifications.setText(pMessage);

        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        menuNotifications.setText("");
    }

    public void jOptionPane(String pMessage){
        JOptionPane.showMessageDialog(this, pMessage);
    }


    /**
     * Updates the shown balance
     */
    public void updateBalance(){
        menuBalance.setText(gameRunner.getPlayerData("balance"));
    }

    /**
     * Adds card of player (main hand) to GUI
     * @param card
     */
    public void addCardPlayer(String[] card){
        playerCardJPanel.add(new CardFrame(card, true), new org.netbeans.lib.awtextra.AbsoluteConstraints(xAxisPlayer, 0, -1, -1));
        xAxisPlayer = xAxisPlayer - 25;
    }

    /**
     * Adds card of player (split hand) to GUI
     * @param card
     */
    public void addCardPlayerSplit(String[] card){
        playerSplitCardJPanel.add(new CardFrame(card, true), new org.netbeans.lib.awtextra.AbsoluteConstraints(xAxisSplitPlayer, 0, -1, -1));
        xAxisSplitPlayer = xAxisSplitPlayer + 25;
        playerSplitCardJPanel.repaint();
        playerSplitCardJPanel.revalidate();
    }

    /**
     * Adds card of player (double) to GUI
     * @param card
     */
    public void addCardPlayerDouble(String[] card){
        playerCardJPanel.add(new CardFrame(card, false), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }

    /**
     * Adds card of dealer to GUI
     * @param card
     */
    public void addCardDealer(String[] card){
        dealerCardJPanel.add(new CardFrame(card, true), new org.netbeans.lib.awtextra.AbsoluteConstraints(xAxisDealer, 0, -1, -1));
        xAxisDealer = xAxisDealer + 25;
    }
    /**
     * Adds blind card of dealer to GUI
     */
    public void addBlindCard(){
        JLabel label = new JLabel();
        label.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("CardBGback.png")));
        dealerCardJPanel.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(xAxisDealer, 0, -1, -1));
        xAxisDealer = xAxisDealer + 25;
    }

    /**
     * Displays the sum of hands
     * @param player
     * @param dealer
     */
    public void displayHands(String player, String dealer){
        menuDealerHandSumInt.setText(dealer);
        menuPlayerHandSumInt.setText(player);
    }

    /**
     * Activates the buttons to play
     * @param active
     */
    public void changeButtonsActivation(boolean active){
        hitButton.setEnabled(active);
        standButton.setEnabled(active);
        doubleButton.setEnabled(active);
        splitButton.setEnabled(active);
    }

    /**
     * Announces winner in notification bar
     * @param winner
     */
    public void announceWinner(String winner){
        menuNotifications.setText(winner);
    }

    /**
     * JOptionPane that asks player for their bet
     */
    public void askforBet() {
        JOptionPane.showMessageDialog(null, "Please enter your bet", "Bet", JOptionPane.PLAIN_MESSAGE);
    }

    /**
     * Removes the Jpanels of player to go into split mode
     */
    public void playerJPanelRemoveAll() {
        playerCardJPanel.removeAll();
        playerCardJPanel.revalidate();
        playerCardJPanel.repaint();
        xAxisPlayer = 197;
        xAxisSplitPlayer = 0;
    }

    /**
     * Removes JPanels of dealer and player to restart game
     * Sets xAxis to default values
     * Clears notification bar
     * Enables all buttons
     */
    public void restartGame(){
        playerCardJPanel.removeAll();
        playerSplitCardJPanel.removeAll();
        dealerCardJPanel.removeAll();
        playerCardJPanel.removeAll();

        playerCardJPanel.revalidate();
        playerCardJPanel.repaint();

        playerSplitCardJPanel.revalidate();
        playerSplitCardJPanel.repaint();

        dealerCardJPanel.revalidate();
        dealerCardJPanel.repaint();

        xAxisPlayer = 197;
        xAxisSplitPlayer = 0;
        xAxisDealer = 0;
        menuNotifications.setText("");
        betPlaced = false;
        menuPlaceBetButton.setEnabled(true);
    }


    /**
     * Retuns username
     * @return
     */
    public String getUserName() {
        return userName;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bG;
    private javax.swing.JLabel doubleButton;
    private javax.swing.JLabel hitButton;
    private javax.swing.JPanel infoMap;
    private javax.swing.JLabel infoMapAchievementsButton;
    private javax.swing.JLabel infoMapBG;
    private javax.swing.JLabel infoMapDailyBonusButton;
    private javax.swing.JLabel infoMapGameGuideButton;
    private javax.swing.JLabel infoMapHistoryButton;
    private javax.swing.JLabel infoMapLogOutButton;
    private javax.swing.JLabel infoMapSettingsButton;
    private javax.swing.JLabel infoMapUsernameLabel;
    private javax.swing.JPanel playerCardJPanel;
    private javax.swing.JPanel playerSplitCardJPanel;
    private javax.swing.JPanel dealerCardJPanel;
    private javax.swing.JLabel menuAccButton;
    private javax.swing.JLabel menuAccName;
    private javax.swing.JLabel menuBalance;
    private javax.swing.JLabel menuBetInputLabel;
    private javax.swing.JTextField menuBetInputTF;
    private javax.swing.JLabel menuDealerHandSum;
    private javax.swing.JLabel menuDealerHandSumInt;
    private javax.swing.JLabel menuNotifications;
    private javax.swing.JLabel menuPlaceBetButton;
    private javax.swing.JLabel menuPlayerHandSum;
    private javax.swing.JLabel menuPlayerHandSumInt;
    private javax.swing.JLabel pF;
    private javax.swing.JLabel splitButton;
    private javax.swing.JLabel standButton;


    // End of variables declaration//GEN-END:variables
}
